// localStorage.setItem("key1","value1")
// localStorage.setItem("key2","value2")
// localStorage.setItem("key3","value3")
// localStorage.setItem("key4","value4")
// localStorage.setItem("key5","value5")
// let user = localStorage.getItem("key2")
// console.log(user)
// localStorage.removeItem("key2")
// localStorage.clear()
// sessionStorage.setItem("key4","value4")
// sessionStorage.setItem("key5","value5")
// sessionStorage.setItem("key6","value6")
// let user2 = sessionStorage.getItem("key5")
// console.log(user2)
// sessionStorage.removeItem("key5")
// sessionStorage.clear()